# Generated by Django 3.2.9 on 2021-12-06 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.IntegerField(default=0)),
                ('twitter', models.IntegerField(default=0)),
                ('instagram', models.IntegerField(default=0)),
                ('snapchat', models.IntegerField(default=0)),
                ('whatsapp', models.IntegerField(default=0)),
                ('reddit', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
